global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /prometheus/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
