version: "3.1"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    container_name: server
    restart: always
    hostname: server
    ports:
      - "8080:8080"
    volumes:
      - "./server:/app"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: client
    restart: always
    hostname: client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "/app/node_modules"

  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    # volumes:
    #   - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alpha-db

  pgadmin:
    image: dpage/pgadmin4:7.0
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - database
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  nginx:
    image: nginx:stable-bullseye
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/*
    environment:
      - FRONTEND_URL=localhost1
      - BACKEND_URL=localhost2

volumes:
  # pgadmin:
  #   name: pgadmin
  #   driver: local
  database:
    name: database
    driver: local
