version: "3.1"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    container_name: server
    restart: always
    hostname: server
    ports:
      - "8080:8080"
    volumes:
      - "./server:/app"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: client
    restart: always
    hostname: client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "/app/node_modules"

  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/*
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - CLIENT_DOMAIN=localhost1
      - SERVER_DOMAIN=localhost2
