version: "3.1"
services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "80:8080"
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_db
# volumes:
#   db:
#     driver: local
