version: "3.1"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
      - "3000:3000"

  database:
    image: postgres:14-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  pgadmin:
    image: dpage/pgadmin4:7.0
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - database
    volumes:
      - ./pgadmin:/var/lib/pgadmin
volumes:
  pgadmin:
    name: pgadmin
    driver: local
  database:
    name: database
    driver: local
