// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
	"time"
)

type Room struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	RoomID     string       `json:"room_id"`
	OwnerID    int32        `json:"owner_id"`
	IsPrivate  bool         `json:"is_private"`
	ExpiredAt  sql.NullTime `json:"expired_at"`
	MaxPlayers int32        `json:"max_players"`
}

type User struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	HashPassword sql.NullString `json:"hash_password"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	OauthID      sql.NullString `json:"oauth_id"`
	OauthType    sql.NullString `json:"oauth_type"`
}
