// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"context"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteRooms(ctx context.Context) error
	DeleteUsers(ctx context.Context) error
	GetRoom(ctx context.Context, id int64) (GetRoomRow, error)
	GetRooms(ctx context.Context, arg GetRoomsParams) ([]GetRoomsRow, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
