name: Docker Build, Push, and Pull

on:
  push:
    branches:
      - main # Adjust this branch name if needed

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nemo0122003/proj-alpha:latest .

      - name: Push Docker image to Docker Hub
        run: docker push nemo0122003/proj-alpha:latest

  pull_and_run_on_droplet:
    name: Pull and Run Docker Image on Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Droplet to known hosts
        run: ssh-keyscan ${{ secrets.PROJECT_IP_ADDRESS}} >> ~/.ssh/known_hosts

      - name: Pull and run Docker image on Droplet
        run: |
          ssh root@${{ secrets.PROJECT_IP_ADDRESS}} 'docker pull nemo0122003/proj-alpha:latest'
          ssh root@${{ secrets.PROJECT_IP_ADDRESS}} 'docker run -d -p 80:80 nemo0122003/proj-alpha:latest'
