name: Project Alpha CI/CD client pipeline

on:
  push:
    branches:
      - main

jobs:
  check_folder_client_changed:
    name: Check if client folder changed
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.changes.outputs.client }}

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            client:
              - 'client/**'

      # run only if "client" files were changed
      - name: client is changed
        if: steps.changes.outputs.client == 'true'
        run: echo "Folder client has changed"

      # run only if "client" files were not changed
      - name: client is not changed
        if: steps.changes.outputs.client == 'false'
        run: echo "Folder client has not changed"

  merge_main_into_vercel_deploy:
    name: Merge main into vercel deploy
    runs-on: ubuntu-latest
    needs: [check_folder_client_changed]
    if: needs.check_folder_client_changed.outputs.is_changed == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge to vercel deploy branch
        run: |
          git checkout vercel-deploy
          git merge main --no-edit
          git push origin vercel-deploy