name: Project Alpha CI/CD monitor config pipeline

on:
  push:
    branches:
      - main

jobs:
  check_folder_monitor_production_changed:
    name: Check if monitor production folder changed
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.changes.outputs.monitor }}

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            monitor:
              - 'monitor/production/**'

      # run only if "monitor production" files were changed
      - name: grafana is changed
        if: steps.changes.outputs.monitor == 'true'
        run: echo "Folder grafana has changed"

      # run only if "grafana" files were not changed
      - name: grafana is not changed
        if: steps.changes.outputs.monitor == 'false'
        run: echo "Folder grafana has not changed"
  
  pull_and_run_on_droplet:
    name: Pull and Run Docker Image on Droplet
    needs: [check_folder_monitor_production_changed]
    if: needs.check_folder_monitor_production_changed.outputs.is_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get services changed
        run: |
          chmod +x ./scripts/get_services_changed.sh
          ./scripts/get_services_changed.sh monitor/production